export const SET_ERROR = 'SET_ERROR';

export const LOAD_MESSAGES_SUCCESS  = 'LOAD_MESSAGES_SUCCESS';
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';
export const EDIT_MESSAGE_SUCCESS   = 'EDIT_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';

export const LOAD_USER_SUCCESS   = 'LOAD_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const LOGIN_USER_SUCCESS  = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';

export const UPDATE_LOGIN_FORM = 'UPDATE_LOGIN_FORM';
export const UNLOAD_LOGIN_FORM = 'UNLOAD_LOGIN_FORM';

export const UPDATE_REGISTER_FORM = 'UPDATE_REGISTER_FORM';
export const UNLOAD_REGISTER_FORM = 'UNLOAD_REGISTER_FORM';

export const UPDATE_CREATE_MESSAGE_FORM = 'UPDATE_CREATE_MESSAGE_FORM';
export const CLEAR_CREATE_MESSAGE_FORM  = 'CLEAR_CREATE_MESSAGE_FORM';
export const UNLOAD_CREATE_MESSAGE_FORM = 'UNLOAD_CREATE_MESSAGE_FORM';
